In [1]:
# Imports
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/laptops.csv")

### Q1 Pandas version

In [3]:
pd.__version__

'1.5.0'

### Q2 How many records?


In [4]:
len(df)

2160

### Q3 How many laptop brands

In [5]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [6]:
df.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [7]:
len(df["Brand"].value_counts())

27

### Q3: Columns with missing values


In [8]:
null_values = df.isnull().sum() # 3
[x for x in df.columns if df[x].isnull().sum() > 0]

['Storage type', 'GPU', 'Screen']

### Q5 : Max data price for Dell

In [9]:
 # df.groupby([["Brand","Model"]]).max()
max_price = df[["Brand","Model","Final Price"]].groupby(["Brand","Model"],as_index= False).max()

In [48]:
max_price[max_price["Brand"] == "Dell"] # 3936

Brand      Model  Final Price
38  Dell   Latitude      2450.71
39  Dell  Precision      3936.00
40  Dell     Vostro      1895.48
41  Dell        XPS      3012.09

### 6

In [15]:
# Find the median value of Screen column in the dataset.
df["Screen"].median(skipna=True)

15.6

In [17]:
np.nanmedian(df["Screen"])

15.6

In [18]:
# Next, calculate the most frequent value of the same Screen column.
mode_val = df["Screen"].mode()
print(mode_val[0])

15.6


In [19]:
df['Screen'] = df['Screen'].replace(['N/A', 'NULL', ''], np.nan)

In [20]:
# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
print(f"Number of missing values before: {df['Screen'].isna().sum()}")
df["Screen"] = df["Screen"].fillna(mode_val[0])
print(f"Number of missing values after: {df['Screen'].isna().sum()}")



Number of missing values before: 4
Number of missing values after: 0


In [21]:
# Now, calculate the median value of Screen once again
median_val2 = df["Screen"].median()
print(median_val2)

15.6


### Q7. Sum of weights

In [29]:
# Select all the "Innjoo" laptops from the dataset.
max_price["Brand"].value_counts().sort_index() # Check spelling of injooo
df_injoo = df[df["Brand"] == "Innjoo"]

In [30]:
# Select only columns RAM, Storage, Screen
df_injoo = df_injoo[["RAM","Storage","Screen"]]

In [31]:
# Get the underlying NumPy array. Let's call it X
X = np.array(df_injoo)

In [33]:
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [37]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX =(X.T).dot(X)

In [39]:
# Compute the inverse of XTX
XTX_i = np.linalg.inv(XTX)

In [40]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100]
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [42]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
w = XTX_i.dot(X.T).dot(y)



In [43]:
# What's the sum of all the elements of the result?
print(f"Suma de pesos: {sum(w)}")

Suma de pesos: 91.2998806299555
